# -*- coding: utf-8 -*-
"""Dataframe.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qplNWaExI51qare11WtsnUv_g8XOv8kD
"""

import yfinance as yf
import pandas as pd

skew_data = yf.download("^SKEW", start="2000-01-01", end="2026-03-09")

print(f"抓到了 {len(skew_data)} 天的数据")
print(skew_data.head())

skew_data.to_csv("CBOE_SKEW_Full_2000_2026.csv")

skew_data = yf.download("^VIX", start="2000-01-01", end="2026-03-09")

print(f"抓到了 {len(skew_data)} 天的数据")
print(skew_data.head())

skew_data.to_csv("VIX.csv")

from google.colab import drive
import os

drive.mount('/content/drive')

df_skew = pd.read_csv("/content/drive/MyDrive/557project/CBOE_SKEW_Full_2000_2026.csv")
df_vix = pd.read_csv("/content/drive/MyDrive/557project/VIX.csv")
df_spread = pd.read_csv("/content/drive/MyDrive/557project/spread_10y2y.csv")
df_oas = pd.read_csv("/content/drive/MyDrive/557project/hy_oas.csv")

# 定义一个列表方便批量操作
dataframes = {
    "SKEW": df_skew,
    "VIX": df_vix,
    "10y-2y Spread": df_spread,
    "HY OAS": df_oas
}

for name, df in dataframes.items():
    print(f"--- {name} ---")
    print(f"行列维度 (Rows, Cols): {df.shape}")
    print("前 3 行预览:")
    display(df.head(3)) # 在 Colab/Jupyter 里用 display 更好看
    print("\n")

df_vix = df_vix.iloc[2:].copy()

df_vix.set_index('Price', inplace=True)
df_vix.index.name = 'Date'

print(df_vix.head())

print(df_skew.head())

for df in [df_spread, df_oas]:
    df.columns = df.columns.str.strip()

for df in [df_spread, df_oas]:
    df['observation_date'] = pd.to_datetime(df['observation_date'])
    df.set_index('observation_date', inplace=True)

print(df_spread.head())
print(df_oas.head())

for df in [df_skew, df_vix]:
    df.index = pd.to_datetime(df.index)

data_final = pd.concat([
    df_skew['Close'].rename('SKEW'),
    df_vix['Close'].rename('VIX'),
    df_spread['T10Y2Y'].rename('Spread'),
    df_oas['BAMLH0A0HYM2'].rename('OAS')
], axis=1)

print(data_final.head())
print(data_final.shape)

print("原始 shape:", data_final.shape)
print("dropna 后 shape:", data_final.dropna().shape)
print("\n每列缺失数：")
print(data_final.isna().sum())

data_model = data_final.dropna().copy()
print(data_model.shape)

data_model.to_csv("4columns_na_dropped.csv")